### ISSUE TITLE
Add kinematics estimation algorithms

### ISSUE THREAD

**Issue by lrapetti** [ami-iit/biomechanical-analysis-framework#4]
- [x] Inverse Velocity Kinematics
- [x] Dynamical Inverse Kinematics 
- [x] Floating-Base Estimation

**Comment by RiccardoGrieco** [comment]
This is being addressed in https://github.com/ami-iit/biomechanical-analysis-framework/tree/add-kin.

The implementation was delayed due to some design overthinking concerning multiple inheritance, choosing between returning references to matrices/vector or filling such objects in methods, responsibility of the data update.

In the end for the first two points I started with a choice since I could not find a winning solution, then I will decide whether other ones seem better.

As for the last point, a the winning solution seems to be avoiding having "update" methods in interfaces and keep them in the implementations, demanding the "update data" chain to the user.

**Comment by claudia-lat** [comment]
@davidegorbani I think that in general the task of IK implementation has been accomplished. Could you please check if this issue can be closed?

**Comment by davidegorbani** [comment]
I think we can close since I checked that the performance of the IK implemented in BAF and HDE are similar (see #22).
